---
name: intel SceneC lassification
author: xiaochen
description: Seventeen flowers classfication
topic: intel SceneC lassification
algorithm: CNN
language: python3
virtualenv: flyai_env/bin/

framework: PyTorch

data:
  id: intelSceneClassification
  name: intel SceneC lassification
  category: image


model:
  processor: Processor
  input_x: input_x
  input_y: input_y
  output_y: output_y
  input:
    columns:
      - name: image_path
        type: string
    to_type: float
    to_shape: [-1, 1]
  output:
    columns:
      - name: label
        type: int
    to_type: float
    to_shape: [-1,6]


evaluate:
  score: torch_accuracy

servers:
 - id: flyai
   url: https://flyai.com
...